id = "miniscript"
name = "MiniScript"
version = "0.0.1"
schema_version = 1
authors = ["ayecue"]
description = "miniscript-lsp extension for Zed"
repository = "https://github.com/ayecue/miniscript-lsp-zed-extension"

[language_servers.miniscript-languageserver]
name = "MiniScript LSP"
language = "MiniScript"

[grammars.miniscript]
repository = "https://github.com/ayecue/tree-sitter-miniscript"
commit = "724ec120d11a7081a9ba4fd163cd57a3e898233a"